import type { AccordionConfig } from "./components/complex/accordion/accordion-config";
import type { AutocompleteConfig } from "./components/complex/autocomplete/autocomplete-config";
import type { CardConfig } from "./components/complex/card/card-config";
import type { CarouselConfig } from "./components/complex/carousel/carousel-config";
import type { ChipConfig } from "./components/complex/chip/chip-config";
import type { DrawerConfig } from "./components/complex/drawer/drawer-config";
import type { KeyboardConfig } from "./components/complex/keyboard/keyboard-config";
import type { MarqueeConfig } from "./components/complex/marquee/marquee-config";
import type { ModalConfig } from "./components/complex/modal/modal-config";
import type { MultiSelectConfig } from "./components/complex/multi-select/multi-select-config";
import type { ResizableScreenConfig } from "./components/complex/resizable-screen/resizable-screen-config";
import type { SidebarConfig } from "./components/complex/sidebar/sidebar-config";
import type { TableConfig } from "./components/complex/table/table-config";
import type { TabsConfig } from "./components/complex/tabs/tabs-config";
import type { ToastConfig } from "./components/complex/toast/toast-config";
import type { TooltipConfig } from "./components/complex/tooltip/tooltip-config";
import type { ButtonConfig } from "./components/primitive/button/button-config";
import type { ContainerConfig } from "./components/primitive/container/container-config";
import type { DatePickerConfig } from "./components/primitive/date-picker/date-picker-config";
import type { FlexConfig } from "./components/primitive/flex/flex-config";
import type { GridConfig } from "./components/primitive/grid/grid-config";
import type { HeadingConfig } from "./components/primitive/heading/heading-config";
import type { ImageConfig } from "./components/primitive/image/image-config";
import type { InputConfig } from "./components/primitive/input/input-config";
import type { LinkConfig } from "./components/primitive/link/link-config";
import type { RadioConfig } from "./components/primitive/radio/radio-config";
import type { SelectConfig } from "./components/primitive/select/select-config";
import type { SpinnerConfig } from "./components/primitive/spinner/spinner-config";
import type { SwitchConfig } from "./components/primitive/switch/switch-config";
import type { TextConfig } from "./components/primitive/text/text-config";
import type { TextAreaConfig } from "./components/primitive/textarea/textarea-config";

export type ComponentConfigRegistry = {
  // Promitive
  container: ContainerConfig;
  flex: FlexConfig;
  grid: GridConfig;
  heading: HeadingConfig;
  text: TextConfig;
  button: ButtonConfig;
  spinner: SpinnerConfig;
  input: InputConfig;
  textarea: TextAreaConfig;
  radio: RadioConfig;
  switch: SwitchConfig;
  datePicker: DatePickerConfig;
  select: SelectConfig;
  image: ImageConfig;
  link: LinkConfig;

  // Complex
  tooltip: TooltipConfig;
  multiSelect: MultiSelectConfig;
  resizableScreen: ResizableScreenConfig;
  tabs: TabsConfig;
  table: TableConfig;
  drawer: DrawerConfig;
  sidebar: SidebarConfig;
  modal: ModalConfig;
  toast: ToastConfig;
  keyboard: KeyboardConfig;
  accordion: AccordionConfig;
  marquee: MarqueeConfig;
  carousel: CarouselConfig;
  card: CardConfig;
  chip: ChipConfig;
  autocomplete: AutocompleteConfig;
};
