/**
 * Tests for the playground distribution command.
 *
 * The distribution is the part of the milestone a client experiences, so its rules
 * are asserted rather than assumed: a target that does not exist is refused, a
 * target that is deferred says why, a directory that already holds files is not
 * written to, and every template is a project the client can install without the
 * repository it came from.
 */

import { existsSync } from "node:fs";
import {
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  executePlaygroundPlan,
  listTemplateFiles,
  renameProject,
} from "../src/lib/playground/copy";
import {
  buildPlaygroundPlan,
  forbiddenProjectPaths,
  projectName,
} from "../src/lib/playground/plan";
import {
  findPlaygroundTarget,
  PLAYGROUND_TARGETS,
  playgroundTargetIds,
  readyPlaygroundTargets,
} from "../src/lib/playground/targets";

/** The CLI package, which holds the templates. */
const packageRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));

/** Targets that can actually be copied. */
const READY = ["next", "vite", "tanstack"] as const;

let dir: string;

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), "ashee-playground-"));
});

afterEach(async () => {
  await rm(dir, { recursive: true, force: true });
});

/**
 * Find relative imports in a template that point at nothing.
 *
 * A template is generated by copying and rewriting, so the way it can be wrong is
 * a specifier that survived a rewrite it should not have, or a module the
 * generation step did not copy. Both leave a project that cannot build, which is
 * why the check is a test rather than a step someone remembers to run.
 *
 * @param root - Absolute path of a template directory.
 * @returns Descriptions of the imports that resolve to no shipped file.
 */
async function unresolvedImports(root: string): Promise<string[]> {
  const problems: string[] = [];
  const candidates = [
    "",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    "/index.ts",
    "/index.tsx",
  ];

  /** Walk one directory. */
  async function walk(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name);

      if (entry.isDirectory()) {
        await walk(path);
        continue;
      }

      if (!/\.tsx?$/.test(entry.name)) continue;

      const source = await readFile(path, "utf8");

      for (const match of source.matchAll(/from "(\.[^"]+)"/g)) {
        const base = match[1].split("?")[0];
        const resolved = candidates.some((suffix) =>
          existsSync(resolve(dirname(path), `${base}${suffix}`)),
        );

        if (!resolved) {
          problems.push(`${path.slice(root.length + 1)} imports ${match[1]}`);
        }
      }
    }
  }

  await walk(root);

  return problems;
}

describe("playground targets", () => {
  it("names every target the command answers for", () => {
    expect(playgroundTargetIds()).toEqual(["next", "vite", "tanstack", "expo"]);
  });

  it("offers the three web playgrounds and defers Expo with a reason", () => {
    expect(readyPlaygroundTargets().map((target) => target.id)).toEqual([
      ...READY,
    ]);

    const expo = findPlaygroundTarget("expo");

    expect(expo?.status).toBe("deferred");
    expect(expo?.reason).toContain("not published yet");
  });

  it("does not find a target that does not exist", () => {
    expect(findPlaygroundTarget("astro")).toBeUndefined();
  });

  it("gives every ready target a template directory of its own name", () => {
    for (const target of PLAYGROUND_TARGETS) {
      if (target.status !== "ready") continue;

      expect(target.template).toBe(target.id);
    }
  });
});

describe("playground plan", () => {
  it("refuses an unknown target", () => {
    const plan = buildPlaygroundPlan({
      targetId: "astro",
      destination: join(dir, "project"),
      packageRoot,
    });

    expect(plan.problems.join(" ")).toContain("Unknown playground");
  });

  it("refuses a deferred target and says why", () => {
    const plan = buildPlaygroundPlan({
      targetId: "expo",
      destination: join(dir, "project"),
      packageRoot,
    });

    expect(plan.problems.join(" ")).toContain("not available yet");
    expect(plan.problems.join(" ")).toContain("not published yet");
  });

  it("names the copied project after the directory it lands in", () => {
    expect(projectName("/home/ada/My Invoices")).toBe("my-invoices");
    expect(projectName("/")).toBe("asheeui-playground");
  });

  it("renames a copied manifest without touching anything else", () => {
    const renamed = renameProject(
      '{"name":"asheeui-playground-next","version":"0.1.0"}',
      "invoices",
    );

    expect(JSON.parse(renamed)).toEqual({ name: "invoices", version: "0.1.0" });
  });
});

describe("playground templates", () => {
  for (const target of READY) {
    it(`${target}: ships a project and nothing of the repository`, async () => {
      const templateRoot = join(packageRoot, "templates", target);
      const files = await listTemplateFiles(templateRoot);

      expect(files).toContain("package.json");
      expect(files.some((file) => file.includes("playground/"))).toBe(true);

      for (const forbidden of forbiddenProjectPaths()) {
        expect(
          files.filter((file) => file.includes(forbidden)),
          `${target} must not carry ${forbidden}`,
        ).toEqual([]);
      }

      const manifest = JSON.parse(
        await readFile(join(templateRoot, "package.json"), "utf8"),
      );
      const dependencies = {
        ...manifest.dependencies,
        ...manifest.devDependencies,
      };

      // The published framework, and nothing that only exists in the repository.
      expect(manifest.dependencies.asheeui).toMatch(/^\^?\d/);
      expect(Object.keys(dependencies)).not.toContain("@asheeui/e2e-gallery");

      for (const name of Object.keys(dependencies)) {
        expect(String(dependencies[name])).not.toContain("workspace:");
      }
    });

    it(`${target}: every relative import resolves inside the project`, async () => {
      expect(
        await unresolvedImports(join(packageRoot, "templates", target)),
      ).toEqual([]);
    });
  }
});

describe("playground distribution", () => {
  it("copies a playground into an empty directory", async () => {
    const destination = join(dir, "invoices");
    const plan = buildPlaygroundPlan({
      targetId: "next",
      destination,
      packageRoot,
    });

    expect(plan.problems).toEqual([]);

    const result = await executePlaygroundPlan(plan);

    expect(result.problems).toEqual([]);
    expect(result.copied).toContain("package.json");

    const manifest = JSON.parse(
      await readFile(join(destination, "package.json"), "utf8"),
    );

    expect(manifest.name).toBe("invoices");
  });

  it("refuses a directory that already holds the project's files", async () => {
    const destination = join(dir, "existing");

    await mkdir(destination, { recursive: true });
    await writeFile(
      join(destination, "package.json"),
      '{"name":"someone-elses-project"}',
      "utf8",
    );

    const plan = buildPlaygroundPlan({
      targetId: "vite",
      destination,
      packageRoot,
    });
    const result = await executePlaygroundPlan(plan);

    expect(result.problems.join(" ")).toContain("already exist");
    expect(result.copied).toEqual([]);

    // The client's own file is untouched, and no partial project was written.
    expect(await readFile(join(destination, "package.json"), "utf8")).toBe(
      '{"name":"someone-elses-project"}',
    );
  });

  it("replaces the files it owns when the caller asks it to, and nothing else", async () => {
    const destination = join(dir, "forced");

    await mkdir(destination, { recursive: true });
    await writeFile(join(destination, "left-alone.txt"), "mine", "utf8");

    const plan = buildPlaygroundPlan({
      targetId: "tanstack",
      destination,
      packageRoot,
      force: true,
    });
    const result = await executePlaygroundPlan(plan);

    expect(result.problems).toEqual([]);
    expect(await readFile(join(destination, "left-alone.txt"), "utf8")).toBe(
      "mine",
    );
  });

  it("reports a missing template instead of writing quietly", async () => {
    const plan = buildPlaygroundPlan({
      targetId: "vite",
      destination: join(dir, "project"),
      packageRoot: join(dir, "not-installed"),
    });
    const result = await executePlaygroundPlan(plan);

    expect(result.problems.join(" ")).toContain(
      "missing from the installed CLI",
    );
  });
});

/**
 * The templates are generated from the playgrounds this repository verifies, so a
 * template that has drifted is a client receiving a playground nobody tested.
 *
 * The comparison below is byte for byte and is driven by the template's own
 * contents rather than by a list kept here: every file the template carries under
 * its playground directory must be the exact file the shared package holds. The
 * shell files around it are rewritten by the generator, so the target test above
 * covers those.
 */
describe("playground template parity", () => {
  for (const target of READY) {
    it(`${target}: ships the shared application this repository verifies`, async () => {
      const templateRoot = join(packageRoot, "templates", target);
      const files = (await listTemplateFiles(templateRoot)).filter((file) =>
        file.includes("playground/"),
      );

      expect(files.length).toBeGreaterThan(0);

      for (const file of files) {
        const module = file.slice(
          file.indexOf("playground/") + "playground/".length,
        );
        const verified = await readFile(
          join(packageRoot, "..", "e2e-gallery", "src", module),
          "utf8",
        );
        const shipped = await readFile(join(templateRoot, file), "utf8");

        expect(
          shipped,
          `${target}: ${module} is not the source this repository verifies`,
        ).toBe(verified);
      }
    });
  }
});
